name: deploy
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-data:
    name: "update data"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: yarn install
      - name: Generate data
        run: yarn run data
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
  # depends-on: [update-data]
  deploy:
    name: "deploy"
    runs-on: ubuntu-latest
    needs: [ update-data ]
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install
        run: yarn install
      - name: Generate website
        run: yarn run website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
